$(document).ready(function(){
    $("#btn-login").click(function(){
        $("#form-popup").show();
});
});
$(document).ready(function(){
    $("#btn-signin").click(function(){
        $("#form-popup2").show();
});
});
